<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>MyTimeSheet - <?php echo $this->header['title'][1] ?></title>

    <!-- Bootstrap -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="/static/bootstrap/js/bootstrap.min.js"></script>
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<div class="container-fluid">
		<div class="row">
		  <div class="col-lg-2 visible-lg-block">
		  </div>
		  <div class="col-xs-12 col-md-12 col-lg-8">
		  	<div class="panel panel-primary">
		  		<div class="panel-heading">
				  	<h1><?php echo $this->header['title'][1] ?>
				  		<?php if(isset($this->header['project-date'])):?>
				  		 <small style="color:white">| starting date : <?php echo isset($this->header['project-date']) ? $this->header['project-date'] : '' ?></small>
				  		<?php endif; ?>
				  	</h1>
				  	<p>
				  		<strong><?php echo $this->header['description'] ?></strong>&nbsp;&nbsp;&nbsp;
				  		<?php if(isset($this->header['week-date'])): ?>
				  		 | starting date : <?php echo isset($this->header['week-date']) ? $this->header['week-date'] : '' ?>
				  		<?php endif; ?>
				  	</p>
			  	</div>
  				<?php  $this->render(); ?>
			  	<div class="panel-footer">
			  	<?php  echo $this->getPlaceholder('content-footer'); ?>
			  	</div>
		  	</div>
		  </div>
		  <div class="col-lg-2 visible-lg-block">
		  </div>
		</div>
	</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>
