#!/usr/bin/env php
<?php

require_once __DIR__.'/autoload.php';
require_once __DIR__.'/bootstrap.php';

set_time_limit(0);


use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use Adem\Sjb\AdemSjbCommands;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$application = new MyTimesheetCommands();
$application->run($input);



